name: BUG提交
description: 如果你觉得这个东西好像不对劲，就提交给我们
labels: ["BUG"]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "确认项"
    description: "请逐个确认下列项目，并勾选确认。"
    options:
    - label: "我确认在我提交这个issuse时这个问题还存在"
    - label: "我确认在issues列表中并无其他人已经提出过与此问题相同或相似的问题"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 遇到的问题
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 期望的结果
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 如何重现此问题？
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: 可能造成问题的原因
    placeholder: "-（若不知道，请填写 “不知道”）-"
- type: textarea
  id: "yml-6"
  attributes:
    label: 系统环境 
    placeholder: "例如：Windows 7 64位 SP1、Windows 10 专业版 64位 1909、Windows 10 家庭版 32位 2002"
  validations:
    required: true
- type: textarea
  id: "yml-7"
  attributes:
    label: 游戏版本版本
    placeholder: "Minecraft的核心版本
    
    例如：Minecraft1.20.X，Minecraft1.20.X Forge"
  validations:
    required: true
- type: textarea
  id: "yml-8"
  attributes:
    label: 模组列表
    placeholder: "你已经安装的模组，例如MTR，Xaero的小地图等"
  validations:
    required: true
- type: textarea
  id: "yml-9"
  attributes:
    label: 模组版本 
    placeholder: "与上面的问题一样，例如MTR3.20.1"
  validations:
    required: true
- type: textarea
  id: "yml-10"
  attributes:
    label: 附注
    placeholder: "还有什么想说的吗？"
